# Introduction

This book is a documentation of the key concepts, findings, and figures of the assigned literature for my qualifying exam. In organizing the literature review in a book, the various concepts are able to be synthesized, interlinked, and mapped to my own research ideas and efforts.

## Research summary

My research interests are broadly focused on parsing apart the relative influence of autochthonous (within the system) vs. allochthonous (from outside of the system) inputs to organic carbon in mangrove sediments. I aim to investigate whether remote sensing and ecoinformatics (standardization and aggregation of disperse field data) can be leveraged to better understand heterogeneity both within- and across-sites.

## Fields of examination

Thus, the topics covered in the exam are namely:

1. Mangrove forest ecology, with an emphasis on regeneration dynamics (Prof. Wayne Sousa)
2. Mangrove soil organic carbon and geomorphology (Prof. Ron Amundson)
3. Remote sensing of wetlands, with a particular focus on mangroves (Prof. Iryna Dronova)
4. Ecoinformatics, tipping points, and decision-making theory (Prof. Carl Boettiger)

## Book format

The book chapters, with subsections for each of the assigned chapters that is identified in a "First author, year of publication" format. Each subsection provides a brief review of the key concepts associated with the article of interest, key findings, and a reprint of any key figures.

## Disclaimer

This book is written for personal use with no commercial gain, and thus all reproduction of figures from published articles are understood to fall under the "fair and other educational use" principle. The syntheses, direct quotes, and images are for the author and his colleagues' own educational reference.
